list: $/soroche/wayna/models/pago/columns.yaml
modelClass: Soroche\Wayna\Models\Pago
title: Pagos
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'soroche/wayna/pagos/update/:id'
