list: $/soroche/wayna/models/embajador/columns.yaml
modelClass: soroche\Wayna\Models\Embajador
title: Embajadores
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'soroche/wayna/embajadores/update/:id'
