servicio_items:
    label: Item
    manage:
        form: $/soroche/wayna/models/servicioitem/actividad_fields.yaml
    view:
        list: $/soroche/wayna/models/servicioitem/actividad_columns.yaml
        toolbarButtons: create|delete