name: Actividades
form: $/soroche/wayna/models/servicio/actividad_fields.yaml
modelClass: soroche\Wayna\Models\Servicio
defaultRedirect: soroche/wayna/actividades
create:
    redirect: 'soroche/wayna/actividades/update/:id'
    redirectClose: soroche/wayna/actividades
update:
    redirect: 'soroche/wayna/actividades/update/:id'
    redirectClose: soroche/wayna/actividades
