list: $/soroche/wayna/models/negocio/columns.yaml
modelClass: Soroche\Wayna\Models\Negocio
title: Negocios
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'soroche/wayna/negocios/update/:id'
