scopes:
    tipo:
        label: Tipo
        type: group
        conditions: tipo in (:filtered)
        options:
            Tour: 'Tour (Actividad)'
            Hotel: Hotel
            Bono: Bono
            Otro: Otro
            Incremento: Incremento
            Descuento: Descuento
    estado:
        label: Estado
        type: group
        conditions: estado in (:filtered)
        options:
            Borrador: Borrador
            Privado: Privado
            Interno: Interno
            Publicado: Publicado
            Deshabilitado: Deshabilitado