list: $/soroche/wayna/models/servicio/paquete_columns.yaml
modelClass: Soroche\Wayna\Models\Servicio
title: Paquetes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'soroche/wayna/paquetes/update/:id'
