list: $/soroche/wayna/models/reserva/columns.yaml
modelClass: Soroche\Wayna\Models\Reserva
title: Reservas
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'soroche/wayna/reservas/update/:id'
