scopes:
    user:
        label: Agente
        modelClass: Backend\Models\User
        conditions: user_id in (:filtered)
        nameFrom: full_name
        permissions: 
            - manage_reservas
    estado:
        label: Estado
        type: group
        conditions: estado in (:filtered)
        options:
            Cotizacion: Cotizacion
            Abierto: Abierto
            Confirmado: Confirmado
            Liquidado: Liquidado
            Anulado: Anulado