name: Reservas
form: $/soroche/wayna/models/reserva/fields.yaml
modelClass: soroche\Wayna\Models\Reserva
defaultRedirect: soroche/wayna/reservas
create:
    redirect: 'soroche/wayna/reservas/update/:id'
    redirectClose: soroche/wayna/reservas
update:
    redirect: soroche/wayna/reservas
    redirectClose: soroche/wayna/reservas
