list: $/soroche/wayna/models/pagopublicidad/columns.yaml
modelClass: Soroche\Wayna\Models\PagoPublicidad
title: Publicidad
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'soroche/wayna/publicidad/update/:id'
