list: $/soroche/wayna/models/servicio/columns.yaml
modelClass: Soroche\Wayna\Models\Servicio
title: Servicios
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'soroche/wayna/servicios/update/:id'
