list: $/soroche/wayna/models/aula/columns.yaml
modelClass: Soroche\Wayna\Models\Aula
title: Entrenamientos
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: false
recordsPerPage: 20
toolbar:
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'soroche/wayna/entrenamientos/preview/:id'
